(define (domain amphipods-domain)
      (:types tile pod - object)
      (:predicates (clear ?t - tile)
                   (at ?p - pod ?t - tile)
                   (tile ?t - tile)
                   (pod ?p - pod)
                   (connected ?a - tile ?b - tile)
                   (outside_room ?t - tile)
                   (room ?t - tile)
                   (hall ?t - tile)
                   (home ?t - tile ?p - pod))
      (:functions (cost) (move_cost ?p - pod))
      (:action move_two_steps
        :parameters (?pod - pod ?from - tile ?a - tile ?to - tile)
        :precondition (and (at ?pod ?from ) 
                           (connected ?from ?a) 
                           (connected ?a ?to) 
                           (or (and (room ?from) (hall ?to))
                               (and (hall ?from) (room ?to) (home ?to ?pod))
                               (and (room ?from) (room ?to) (home ?to ?pod))) 
                           (clear ?a) 
                           (clear ?to) 
                           (not (outside_room ?to)))
        :effect (and (not (at ?pod ?from))
                     (clear ?from)
                     (not (clear ?to))
                     (at ?pod ?to)
                     (increase (cost) (* (move_cost ?pod) 2 )))
      )
      (:action move_three_steps
        :parameters (?pod - pod ?from - tile ?a - tile ?b - tile ?to - tile)
        :precondition (and (at ?pod ?from ) 
                           (connected ?from ?a)
                           (connected ?a ?b)
                           (connected ?b ?to)
                           (!= ?from ?b)
                           (!= ?to ?a)
                           (or (and (room ?from) (hall ?to))
                               (and (hall ?from) (room ?to) (home ?to ?pod))
                               (and (room ?from) (room ?to) (home ?to ?pod))) 
                           (clear ?a)
                           (clear ?b) 
                           (clear ?to) 
                           (not (outside_room ?to)))
        :effect (and (not (at ?pod ?from))
                     (clear ?from)
                     (not (clear ?to))
                     (at ?pod ?to)
                     (increase (cost) (* (move_cost ?pod) 3 )))
      )
      (:action move_four_steps
        :parameters (?pod - pod ?from - tile ?a - tile ?b - tile ?c - tile ?to - tile)
        :precondition (and (at ?pod ?from ) 
                           (connected ?from ?a)
                           (connected ?a ?b)
                           (connected ?b ?c)
                           (connected ?c ?to)
                           (!= ?from ?b)
                           (!= ?from ?c)
                           (!= ?to ?a)
                           (!= ?to ?b)
                           (!= ?a ?c)
                           (or (and (room ?from) (hall ?to))
                               (and (hall ?from) (room ?to) (home ?to ?pod))
                               (and (room ?from) (room ?to) (home ?to ?pod))) 
                           (clear ?a)
                           (clear ?b)
                           (clear ?c) 
                           (clear ?to) 
                           (not (outside_room ?to)))
        :effect (and (not (at ?pod ?from))
                     (clear ?from)
                     (not (clear ?to))
                     (at ?pod ?to)
                     (increase (cost) (* (move_cost ?pod) 4 )))
      )
      (:action move_five_steps
        :parameters (?pod - pod ?from - tile ?a - tile ?b - tile ?c - tile ?d - tile ?to - tile)
        :precondition (and (at ?pod ?from ) 
                           (connected ?from ?a)
                           (connected ?a ?b)
                           (connected ?b ?c)
                           (connected ?c ?d)
                           (connected ?d ?to)
                           (!= ?from ?b)
                           (!= ?from ?c)
                           (!= ?from ?d)
                           (!= ?to ?a)
                           (!= ?to ?b)
                           (!= ?to ?c)
                           (!= ?a ?c)
                           (!= ?a ?d)
                           (!= ?b ?d)
                           (or (and (room ?from) (hall ?to))
                               (and (hall ?from) (room ?to) (home ?to ?pod))
                               (and (room ?from) (room ?to) (home ?to ?pod))) 
                           (clear ?a)
                           (clear ?b)
                           (clear ?c) 
                           (clear ?d)
                           (clear ?to) 
                           (not (outside_room ?to)))
        :effect (and (not (at ?pod ?from))
                     (clear ?from)
                     (not (clear ?to))
                     (at ?pod ?to)
                     (increase (cost) (* (move_cost ?pod) 5 )))
      )
      (:action move_six_steps
        :parameters (?pod - pod ?from - tile ?a - tile ?b - tile ?c - tile ?d - tile ?e - tile ?to - tile)
        :precondition (and (at ?pod ?from ) 
                           (connected ?from ?a)
                           (connected ?a ?b)
                           (connected ?b ?c)
                           (connected ?c ?d)
                           (connected ?d ?e)
                           (connected ?e ?to)
                           (!= ?from ?b)
                           (!= ?from ?c)
                           (!= ?from ?d)
                           (!= ?from ?e)
                           (!= ?to ?a)
                           (!= ?to ?b)
                           (!= ?to ?c)
                           (!= ?to ?d)
                           (!= ?a ?c)
                           (!= ?a ?d)
                           (!= ?a ?e)
                           (!= ?b ?d)
                           (!= ?b ?e)
                           (!= ?c ?e)
                           (or (and (room ?from) (hall ?to))
                               (and (hall ?from) (room ?to) (home ?to ?pod))
                               (and (room ?from) (room ?to) (home ?to ?pod))) 
                           (clear ?a)
                           (clear ?b)
                           (clear ?c) 
                           (clear ?d)
                           (clear ?e)
                           (clear ?to) 
                           (not (outside_room ?to)))
        :effect (and (not (at ?pod ?from))
                     (clear ?from)
                     (not (clear ?to))
                     (at ?pod ?to)
                     (increase (cost) (* (move_cost ?pod) 6 )))
      )
      (:action move_seven_steps
        :parameters (?pod - pod ?from - tile ?a - tile ?b - tile ?c - tile ?d - tile ?e - tile ?f - tile ?to - tile)
        :precondition (and (at ?pod ?from ) 
                           (connected ?from ?a)
                           (connected ?a ?b)
                           (connected ?b ?c)
                           (connected ?c ?d)
                           (connected ?d ?e)
                           (connected ?e ?f)
                           (connected ?f ?to)
                           (!= ?from ?b)
                           (!= ?from ?c)
                           (!= ?from ?d)
                           (!= ?from ?e)
                           (!= ?from ?f)
                           (!= ?to ?a)
                           (!= ?to ?b)
                           (!= ?to ?c)
                           (!= ?to ?d)
                           (!= ?to ?e)
                           (!= ?a ?c)
                           (!= ?a ?d)
                           (!= ?a ?e)
                           (!= ?a ?f)
                           (!= ?b ?d)
                           (!= ?b ?e)
                           (!= ?b ?f)
                           (!= ?c ?e)
                           (!= ?c ?f)
                           (!= ?d ?f)
                           (or (and (room ?from) (hall ?to))
                               (and (hall ?from) (room ?to) (home ?to ?pod))
                               (and (room ?from) (room ?to) (home ?to ?pod))) 
                           (clear ?a)
                           (clear ?b)
                           (clear ?c) 
                           (clear ?d)
                           (clear ?e)
                           (clear ?f)
                           (clear ?to) 
                           (not (outside_room ?to)))
        :effect (and (not (at ?pod ?from))
                     (clear ?from)
                     (not (clear ?to))
                     (at ?pod ?to)
                     (increase (cost) (* (move_cost ?pod) 7 )))
      )
      (:action move_eight_steps
        :parameters (?pod - pod ?from - tile ?a - tile ?b - tile ?c - tile ?d - tile ?e - tile ?f - tile ?g - tile ?to - tile)
        :precondition (and (at ?pod ?from ) 
                           (connected ?from ?a)
                           (connected ?a ?b)
                           (connected ?b ?c)
                           (connected ?c ?d)
                           (connected ?d ?e)
                           (connected ?e ?f)
                           (connected ?f ?g)
                           (connected ?g ?to)
                           (!= ?from ?b)
                           (!= ?from ?c)
                           (!= ?from ?d)
                           (!= ?from ?e)
                           (!= ?from ?f)
                           (!= ?from ?g)
                           (!= ?to ?a)
                           (!= ?to ?b)
                           (!= ?to ?c)
                           (!= ?to ?d)
                           (!= ?to ?e)
                           (!= ?to ?f)
                           (!= ?a ?c)
                           (!= ?a ?d)
                           (!= ?a ?e)
                           (!= ?a ?f)
                           (!= ?a ?g)
                           (!= ?b ?d)
                           (!= ?b ?e)
                           (!= ?b ?f)
                           (!= ?b ?g)
                           (!= ?c ?e)
                           (!= ?c ?f)
                           (!= ?c ?g)
                           (!= ?d ?f)
                           (!= ?d ?g)
                           (!= ?e ?g)
                           (or (and (room ?from) (hall ?to))
                               (and (hall ?from) (room ?to) (home ?to ?pod))
                               (and (room ?from) (room ?to) (home ?to ?pod))) 
                           (clear ?a)
                           (clear ?b)
                           (clear ?c) 
                           (clear ?d)
                           (clear ?e)
                           (clear ?f)
                           (clear ?g)
                           (clear ?to) 
                           (not (outside_room ?to)))
        :effect (and (not (at ?pod ?from))
                     (clear ?from)
                     (not (clear ?to))
                     (at ?pod ?to)
                     (increase (cost) (* (move_cost ?pod) 8 )))
      )
)