(define (problem day23example) (:domain amphipods-domain)
    (:objects 
        amber1 amber2 bronze1 bronze2 copper1 copper2 desert1 desert2 - pod
        hall1 hall2 hall3 hall4 hall5 hall6 hall7 hall8 hall9 hall10 hall11 room1a room1b room2a room2b room3a room3b room4a room4b - tile
    )

    (:init
        (= (cost) 0)
        (= (move_cost amber1) 1)
        (= (move_cost amber1) 1)
        (= (move_cost bronze1) 10)
        (= (move_cost bronze2) 10)
        (= (move_cost copper1) 100)
        (= (move_cost copper2) 100)
        (= (move_cost desert1) 1000)
        (= (move_cost desert2) 1000)
        (outside_room hall3)
        (outside_room hall5)
        (outside_room hall7)
        (outside_room hall9)
        (connected hall3 room1a)
        (connected hall5 room2a)
        (connected hall7 room3a)
        (connected hall9 room4a)
        (connected room1a room1b)
        (connected room2a room2b)
        (connected room3a room3b)
        (connected room4a room4b)
        (connected hall2 hall1)
        (connected hall3 hall2)
        (connected hall4 hall3)
        (connected hall5 hall4)
        (connected hall6 hall5)
        (connected hall7 hall6)
        (connected hall8 hall7)
        (connected hall9 hall8)
        (connected hall10 hall9)
        (connected hall11 hall10)
        (connected room1a hall3)
        (connected room2a hall5)
        (connected room3a hall7)
        (connected room4a hall9)
        (connected room1b room1a)
        (connected room2b room2a)
        (connected room3b room3a)
        (connected room4b room4a)
        (connected hall1 hall2)
        (connected hall2 hall3)
        (connected hall3 hall4)
        (connected hall4 hall5)
        (connected hall5 hall6)
        (connected hall6 hall7)
        (connected hall7 hall8)
        (connected hall8 hall9)
        (connected hall9 hall10)
        (connected hall10 hall11)
        (hall hall1)
        (hall hall2)
        (hall hall3)
        (hall hall4)
        (hall hall5)
        (hall hall6)
        (hall hall7)
        (hall hall8)
        (hall hall9)
        (hall hall10)
        (hall hall11)
        (room room1a)
        (room room2a)
        (room room3a)
        (room room4a)
        (room room1b)
        (room room2b)
        (room room3b)
        (room room4b)
        (home room1a amber1)
        (home room2a bronze1)
        (home room3a copper1)
        (home room4a desert1)
        (home room1b amber1)
        (home room2b bronze1)
        (home room3b copper1)
        (home room4b desert1)
        (home room1a amber2)
        (home room2a bronze2)
        (home room3a copper2)
        (home room4a desert2)
        (home room1b amber2)
        (home room2b bronze2)
        (home room3b copper2)
        (home room4b desert2)

        (at bronze1 room1a)
        (at amber1 room1b)
        (at copper1 room2a)
        (at desert1 room2b)
        (at bronze2 room3a)
        (at copper2 room3b)
        (at desert2 room4a)
        (at amber2 room4b)
        (clear hall1)
        (clear hall2)
        (clear hall3)
        (clear hall4)
        (clear hall5)
        (clear hall6)
        (clear hall7)
        (clear hall8)
        (clear hall9)
        (clear hall10)
        (clear hall11)
    )


    (:goal
        (and
            (or (and (at amber1 room1a) (at amber2 room1b))
                (and (at amber2 room1a) (at amber1 room1b)))

            (or (and (at bronze1 room2a) (at bronze2 room2b))
                (and (at bronze2 room2a) (at bronze1 room2b)))

            (or (and (at copper1 room3a) (at copper2 room3b))
                (and (at copper2 room3a) (at copper1 room3b)))

            (or (and (at desert1 room4a) (at desert2 room4b))
                (and (at desert2 room4a) (at desert1 room4b)))
        )
    )

    (:metric minimize(cost))
)